version: '2'

services:
  # base:
  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.17.0.RELEASE
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: eventuateio/eventuateio-local-kafka:0.17.0.RELEASE
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
      - ZOOKEEPER_SERVERS=zookeeper:2181

  # ermp:
  ermp-mysql:
    image: eventuateio/eventuate-tram-sagas-mysql:0.5.0.RELEASE
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  
  ermp-cdcservice:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.6.0.RELEASE
    expose:
      - 8080
    links:
      - kafka
      - ermp-mysql
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://ermp-mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  ermp-service:
    build: ./
    image: aker/tram-examples-ermp
    ports:
      - 8180:8180
    links:
      - kafka
      - ermp-mysql
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://ermp-mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
